name: firebase_manager
description: A package to manage Firebase easily.
version: 0.0.3
homepage: https://github.com/normidar-group/normidar_dart_series/tree/main/apps/firebase_manager

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.1.0

  fm_auth: ^0.0.1
  fm_storage: ^0.0.1

  # Firebase realtime database
  firebase_database: ^10.3.6

  firebase_app_check: ^0.2.1+1

  # for log
  firebase_analytics: ^10.0.2

  firebase_messaging: ^14.7.10

  firebase_crashlytics: ^3.0.2

  # create link to register by email
  firebase_dynamic_links: ^5.0.17

  # fire store
  cloud_firestore: ^4.4.5

  # firebase ui
  firebase_ui_localizations: ^1.5.0


  collection: ^1.17.2
  cloud_firestore_platform_interface: ^6.0.7
  json_annotation: ^4.8.1
  firebase_messaging_platform_interface: ^4.5.18

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0

  auto_exporter: ^3.0.0
  build_runner: ^2.4.6
  build_test: ^2.2.0

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
